# Generated by Django 5.0.2 on 2024-02-10 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Audio_store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record', models.FileField(null=True, upload_to='documents/')),
            ],
            options={
                'db_table': 'Audio_store',
            },
        ),
    ]
