# Generated by Django 5.0.2 on 2024-02-10 02:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_audio_store'),
    ]

    operations = [
        migrations.AddField(
            model_name='audio_store',
            name='prescription',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audio_store', to='base.prescription'),
        ),
        migrations.AlterField(
            model_name='audio_store',
            name='record',
            field=models.FileField(upload_to='documents/'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='aadhar_number',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterModelTable(
            name='audio_store',
            table=None,
        ),
    ]
